### ISSUE TITLE
how is this different from "postcss-js" ?

### ISSUE THREAD

**Issue by stevenvachon** [staxmanade/CssToReact#1]
https://www.npmjs.com/package/postcss-js

**Comment by staxmanade** [comment]
It's not a package or library. It's a simple online tool for copy/paste. For use in easy one-off's you need to translate. (Just a tool I'd wanted to use in the past and didn't see anywhere). 

Hope that helps.

Actually, thanks for sharing. I wonder if I should consider using postcss-js under the hood in this project :)
