### ISSUE TITLE
How do I run the project locally?

### ISSUE THREAD

**Issue by wildeyes** [staxmanade/CssToReact#3]

**Comment by staxmanade** [comment]
try `npm run build` then just run any static site hosting web server like `npm install -g nws` then `nws -o`

**Comment by tongrhj** [comment]
```
npm install
npm run build
1st error: jspm not found
npm install jspm --save-dev
npm run build
2nd error: No project configuration file not found. Looking for: [project_path]/config.js
mv jspm.config.js config.js
npm run build
Building the bundle tree for app - react - react-dom...
3rd error: Error on fetch for app at [project_path]/app
        Error: ENOENT: no such file or directory, open '[project_path]/app'
         at Error (native)
```

No such path was created. Never tried it before, so investigating how jspm works atm to debug.
jspm version installed: `0.16.45`

**Comment by staxmanade** [comment]
Hey - sorry for not making this a little easier to get started. I just pushed up a change to the project's readme that I think might help. Can you give that a go?

I think you might potentially be running into issues with the version of JSPM (the new beta versions are the way to go...)

**Comment by tongrhj** [comment]
Yes, it was the version of JSPM! Though that solved the error above, I then ran into an issue:

```
err  Error on translate for app.jsx at file:///[project_path]/src/app.jsx
  TypeError: Path must be a string. Received undefined
```

Tracked it down to a Node 6 compatibility issue with plugin-babel (see [issue](https://github.com/systemjs/plugin-babel/issues/34)). Updating it to the latest version (0.0.13) worked. Submitted a PR with these changes: https://github.com/staxmanade/CssToReact/pull/4

**Comment by staxmanade** [comment]
Thanks for the feedback (as code)
